# select language
language: cpp

# install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# build code for test, test, and create documentation
script:
  - make && make test
  - make doc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  # no need for history as long as we are on the right branch
  keep-history: false
  target-branch: gh-pages
  on:
    branch: master
  local-dir: html
